package com.lamda.projectnotes.ui.theme

import androidx.compose.ui.graphics.Color


/*Light colors might still needs some work, have not tested
some colors variants for example, on error */
val md_theme_light_primary = Color(0xFF192336)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF192336)
val md_theme_light_onPrimaryContainer = Color(0xFFFFFFFF)
val md_theme_light_secondary = Color(0xFFEDEDEF)
val md_theme_light_onSecondary = Color(0xFF192336)
val md_theme_light_secondaryContainer = Color(0xFF192336)
val md_theme_light_onSecondaryContainer = Color(0xFFFFFFFF)
val md_theme_light_tertiary = Color(0xFF7D5260)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD8E4)
val md_theme_light_onTertiaryContainer = Color(0xFF31111D)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_outline = Color(0xFF192336)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF192336)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF192336)
val md_theme_light_surfaceVariant = Color(0xFFEFEDED)
val md_theme_light_onSurfaceVariant = Color(0xFF192336)
val md_theme_light_inverseSurface = Color(0xFF192336)
val md_theme_light_inverseOnSurface = Color(0xFFFFFFFF)
val md_theme_light_inversePrimary = Color(0xFFEFEDED)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF192336)
val md_theme_light_outlineVariant = Color(0xFFD0C4C4)
val md_theme_light_scrim = Color(0xFF000000)


/* Dark Color not implemented yet */
val md_theme_dark_primary = Color(0xFFD0BCFF)
val md_theme_dark_onPrimary = Color(0xFF381E72)
val md_theme_dark_primaryContainer = Color(0xFF4F378B)
val md_theme_dark_onPrimaryContainer = Color(0xFFEADDFF)
val md_theme_dark_secondary = Color(0xFFCCC2DC)
val md_theme_dark_onSecondary = Color(0xFF332D41)
val md_theme_dark_secondaryContainer = Color(0xFF4A4458)
val md_theme_dark_onSecondaryContainer = Color(0xFFE8DEF8)
val md_theme_dark_tertiary = Color(0xFFEFB8C8)
val md_theme_dark_onTertiary = Color(0xFF492532)
val md_theme_dark_tertiaryContainer = Color(0xFF633B48)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD8E4)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_background = Color(0xFF1C1B1F)
val md_theme_dark_onBackground = Color(0xFFE6E1E5)
val md_theme_dark_surface = Color(0xFF1C1B1F)
val md_theme_dark_onSurface = Color(0xFFE6E1E5)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E5)
val md_theme_dark_inverseOnSurface = Color(0xFF313033)
val md_theme_dark_inversePrimary = Color(0xFF6750A4)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFD0BCFF)
val md_theme_dark_outlineVariant = Color(0xFF49454F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF6750A4)


val Orange80 = Color(0xFFF5EBDD)
val Aqua80 = Color(0xFFEDF6F5)
val Turquoise80 = Color(0xFFE7EEDD)
val Red80 = Color(0xFFFCD4D4)
val Rose80 = Color(0xFFFCDFFB)
val Lime80 = Color(0xFFECEEB2)
val Grey80 = Color(0xFFE8E8E8)
val White80 = Color(0xFFFFFFFF)
